name: Deploy Jarvis Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bandit (SAST Security Check)
        # Проверяем только наш код (app и main.py), игнорируем тесты и виртуальное окружение
        run: bandit -r app/ main.py

      - name: Run Pytest
        env:
          BOT_TOKEN: "test_token"
          MY_ID: "12345"
          MY_EMAIL: "test@example.com"
          MY_CITY: "Moscow"
          MY_TIME_ZONE: "Europe/Moscow"
          MY_REGION: "test_region"
          RSS_SITE: "http://test.rss"
          OWM_API_KEY: "test_key"
          AI_API_KEY: "fake_key" 
        run: pytest tests/ -v
  deploy:
    needs: test_and_security # Ждет успешного завершения job'ы test_and_security
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Выполняется ТОЛЬКО при пуше или мерже в main
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.WORK_DIR }}
            git pull origin main
            docker compose up --build -d